# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: userid.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import userinfo_pb2 as userinfo__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='userid.proto',
  package='grpc',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cuserid.proto\x12\x04grpc\x1a\x0euserinfo.proto\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\x05\x32\x35\n\x04User\x12-\n\x0bGetUserInfo\x12\x0c.grpc.UserId\x1a\x0e.grpc.UserInfo\"\x00\x62\x06proto3')
  ,
  dependencies=[userinfo__pb2.DESCRIPTOR,])




_USERID = _descriptor.Descriptor(
  name='UserId',
  full_name='grpc.UserId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='grpc.UserId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['UserId'] = _USERID
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserId = _reflection.GeneratedProtocolMessageType('UserId', (_message.Message,), dict(
  DESCRIPTOR = _USERID,
  __module__ = 'userid_pb2'
  # @@protoc_insertion_point(class_scope:grpc.UserId)
  ))
_sym_db.RegisterMessage(UserId)



_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='grpc.User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=60,
  serialized_end=113,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetUserInfo',
    full_name='grpc.User.GetUserInfo',
    index=0,
    containing_service=None,
    input_type=_USERID,
    output_type=userinfo__pb2._USERINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
